apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: am-transaction-api
  description: AM Transaction API
spec:
  type: openapi
  lifecycle: production
  owner: amit.khurana@africa.airtel.com
  definition: |
    swagger: '2.0'
    info:
      description: This service handles all airtel money transaction services
      version: API 1.0
      title: Airtel Money Transactions Service
      termsOfService: TERMS OF SERVICE
      contact:
        name: Anuj
      license:
        name: LICENSE OF API
        url: API LICENSE URL
    host: 'merchantsuat.airtel.africa'
    basePath: /
    tags:
      - name: Merchant Initiated Transation (USSD Push)
        description: 'This Controller will be used for Initiating Payment, Callback, Transation status APIs for Group Merchant USSD Push.'
    paths:
      /v1/payments:
        post:
          tags:
            - Merchant Initiated Transation (USSD Push)
          summary: Initiate Payment API
          description: API will be used to initiate the payment.
          operationId: initiatePaymentUsingPOST
          consumes:
            - application/json
          produces:
            - '*/*'
          parameters:
            - name: X-API-Key
              in: header
              required: true
              type: string
              default: 84cbd62d-81b8-47b4-a281-349ca8796105 
            - name: Authorization
              in: header
              required: true
              type: string
              default: Bearer qetqnH3Ic8
            - name: Content-Type
              in: header
              required: true
              type: string
              default: application/json
            - in: body
              name: intiatePaymentRequest
              description: intiatePaymentRequest
              required: true
              schema:
                $ref: '#/definitions/InitiatePaymentRequest'
          responses:
            '200':
              description: OK
              schema:
                $ref: '#/definitions/WrapperResponse'
            '201':
              description: Created
            '401':
              description: Unauthorized
            '403':
              description: Forbidden
            '404':
              description: Not Found
          deprecated: false
      /v1/payments/status:
        post:
          tags:
            - Merchant Initiated Transation (USSD Push)
          summary: Transaction Status API
          description: API will be used to get the status of the transaction.
          operationId: transactionStatusUsingPOST
          consumes:
            - application/json
          produces:
            - '*/*'
          parameters:
            - name: X-API-Key
              in: header
              required: true
              type: string
              default: 84cbd62d-81b8-47b4-a281-349ca8796105 
            - name: Authorization
              in: header
              required: true
              type: string
              default: Bearer qetqnH3Ic8
            - name: Content-Type
              in: header
              required: true
              type: string
              default: application/json
            - in: body
              name: transactionStatusRequest
              description: transactionStatusRequest
              required: true
              schema:
                $ref: '#/definitions/TransactionStatusRequest'
          responses:
            '200':
              description: OK
              schema:
                $ref: '#/definitions/WrapperResponse«Callback»'
            '201':
              description: Created
            '401':
              description: Unauthorized
            '403':
              description: Forbidden
            '404':
              description: Not Found
          deprecated: false
    definitions:
      Aggregator:
        type: object
        required:
          - country
          - currency
          - name
        properties:
          country:
            type: string
            description: Country of the Aggregator.
          currency:
            type: string
            description: Currency of the Aggregator's country.
          name:
            type: string
            description: Name of the Aggregator.
        title: Aggregator
      Callback:
        type: object
        properties:
          external_txn_id:
            type: string
            description: The Transaction Id generated by Aggregator.
          txn:
            description: Transaction response from AM.
            $ref: '#/definitions/TransactionStatus'
        title: Callback
      CallbackRequest:
        type: object
        properties:
          ext_trid:
            type: string
          interface_id:
            type: string
          message:
            type: string
          msisdn2:
            type: string
          txn_id:
            type: string
          txn_status:
            type: string
          type:
            type: string
        title: CallbackRequest
      Error:
        type: object
        properties:
          code:
            type: string
            description: Error code.
          message:
            type: string
            description: Error message.
        title: Error
      InitiatePaymentRequest:
        type: object
        required:
          - aggregator
          - external_txn
          - reference
          - subscriber
        properties:
          aggregator:
            description: Aggregator Object.
            $ref: '#/definitions/Aggregator'
          external_txn:
            description: Transaction Object.
            $ref: '#/definitions/Transaction'
          memo:
            type: string
          reference:
            type: string
            description: Reference for service/goods purchased
          subscriber:
            description: Subscriber Object.
            $ref: '#/definitions/Subscriber'
        title: InitiatePaymentRequest
      Subscriber:
        type: object
        required:
          - country
          - currency
          - msisdn
        properties:
          country:
            type: string
            description: Country of the Subscriber.
          currency:
            type: string
            description: Currency of the Subscriber's country.
          msisdn:
            type: string
            description: Subscriber MSISDN without Country Code.
        title: Subscriber
      Transaction:
        type: object
        required:
          - amount
          - id
        properties:
          amount:
            type: integer
            format: int32
            description: Amount to credit/debit without currency and format. Plain digit like 1000.
          id:
            type: string
            description: Generated Transaction Id.
        title: Transaction
      TransactionStatus:
        type: object
        required:
          - id
        properties:
          id:
            type: string
            description: Generated Transaction Id.
          message:
            type: string
            description: Description message of transaction status.
          status:
            type: string
            description: Transaction status.
        title: TransactionStatus
      TransactionStatusRequest:
        type: object
        required:
          - aggregator_name
          - external_txn_id
          - subscriber_country
        properties:
          aggregator_name:
            type: string
            xml:
              name: INTERFACEID
              attribute: false
              wrapped: false
            description: Name of the Aggregator.
          external_txn_id:
            type: string
            xml:
              name: EXTTRID
              attribute: false
              wrapped: false
            description: The Transaction Id against which payment was initiated.
          subscriber_country:
            type: string
            description: Country of the Subscriber.
        title: TransactionStatusRequest
        xml:
          name: COMMAND
          attribute: false
          wrapped: false
      WrapperResponse:
        type: object
        properties:
          data:
            type: object
            description: Contains data if any.
          errors:
            type: array
            description: List of errors.
            items:
              $ref: '#/definitions/Error'
          status_code:
            type: integer
            format: int32
            description: Status code.
          success:
            type: boolean
            description: true if success else false.
        title: WrapperResponse
      WrapperResponse«Callback»:
        type: object
        properties:
          data:
            description: Contains data if any.
            $ref: '#/definitions/Callback'
          errors:
            type: array
            description: List of errors.
            items:
              $ref: '#/definitions/Error'
          status_code:
            type: integer
            format: int32
            description: Status code.
          success:
            type: boolean
            description: true if success else false.
        title: WrapperResponse«Callback»
      WrapperResponse«object»:
        type: object
        properties:
          data:
            type: object
            description: Contains data if any.
          errors:
            type: array
            description: List of errors.
            items:
              $ref: '#/definitions/Error'
          status_code:
            type: integer
            format: int32
            description: Status code.
          success:
            type: boolean
            description: true if success else false.
        title: WrapperResponse«object»
