apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web1
  description: The place to be, for great artists1
spec:
  type: service
  lifecycle: production
  owner: guest
  implementsApis:
    - am-transaction-api
