apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Test
  description: Test
  annotations:
    backstage.io/techdocs-ref: dir:./
  tags:
    - java
    - playback
spec:
  type: service
  lifecycle: production
  owner: guest
